%% Save positions and orientations and turn them into poses

function [waypoints,number_waypoints] = setWaypoints()
%Get positions declare w.r.t Global reference
% positions=      [0,-0.27,0.38;...
%                 -0.5,-0.3,0.4;...
%                 0,-0.3,0.2;...
%                 0.5,-0.3,0.4];
positions=      [-0.5,-0.3,0.4;...
                0,-0.3,0.2;...
                0.5,-0.3,0.4];
%Get orientations(in rotation vector)        
%orientations=   [0,1,0,pi;...
%                 0,1,0,pi;...
%                 0,1,0,pi;...
%                 0,1,0,pi];
orientations=   [0,1,0,pi;...
                0,1,0,pi;...
                0,1,0,pi];

%Get number of positions
number_waypoints=size(positions,1);

% Reserve memory
waypoints=zeros(4,4,number_waypoints);

% Get poses with positions and orientations
waypoints(:,:,:)=pagemtimes(trvec2tform(positions(:,:)),axang2tform(orientations(:,:)));
end

