set_target_payload(0.000000, [0.000000, 0.000000, 0.000000], [0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000])
set_tcp(p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_safety_mode_transition_hardness(1)
set_gravity([0.0, 0.0, 9.82])
step_count_dbc8a954_3a74_46e2_8731_ad049eed2381 = 0.0
thread Step_Counter_Thread_eae57136_027f_4a92_8e95_53c882d90bbf():
  while (True):
    step_count_dbc8a954_3a74_46e2_8731_ad049eed2381 = step_count_dbc8a954_3a74_46e2_8731_ad049eed2381 + 1.0
    sync()
  end
end

run Step_Counter_Thread_eae57136_027f_4a92_8e95_53c882d90bbf()
set_standard_analog_input_domain(0, 1)
set_standard_analog_input_domain(1, 1)
set_tool_analog_input_domain(0, 1)
set_tool_analog_input_domain(1, 1)
set_analog_outputdomain(0, 0)
set_analog_outputdomain(1, 0)
set_input_actions_to_default()
set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
set_tool_output_mode(0)
set_tool_digital_output_mode(0, 1)
set_tool_digital_output_mode(1, 1)
set_tool_voltage(0)